# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x0fpayment_service\"L\n\x15PaymentPrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x11\n\tuser_name\x18\x03 \x01(\t\">\n\x16PaymentPrepareResponse\x12\x13\n\x0bvote_commit\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x14PaymentCommitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"9\n\x15PaymentCommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\x13PaymentAbortRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"8\n\x14PaymentAbortResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9b\x02\n\x0ePaymentService\x12Z\n\x07Prepare\x12&.payment_service.PaymentPrepareRequest\x1a\'.payment_service.PaymentPrepareResponse\x12W\n\x06\x43ommit\x12%.payment_service.PaymentCommitRequest\x1a&.payment_service.PaymentCommitResponse\x12T\n\x05\x41\x62ort\x12$.payment_service.PaymentAbortRequest\x1a%.payment_service.PaymentAbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTPREPAREREQUEST']._serialized_start=34
  _globals['_PAYMENTPREPAREREQUEST']._serialized_end=110
  _globals['_PAYMENTPREPARERESPONSE']._serialized_start=112
  _globals['_PAYMENTPREPARERESPONSE']._serialized_end=174
  _globals['_PAYMENTCOMMITREQUEST']._serialized_start=176
  _globals['_PAYMENTCOMMITREQUEST']._serialized_end=216
  _globals['_PAYMENTCOMMITRESPONSE']._serialized_start=218
  _globals['_PAYMENTCOMMITRESPONSE']._serialized_end=275
  _globals['_PAYMENTABORTREQUEST']._serialized_start=277
  _globals['_PAYMENTABORTREQUEST']._serialized_end=316
  _globals['_PAYMENTABORTRESPONSE']._serialized_start=318
  _globals['_PAYMENTABORTRESPONSE']._serialized_end=374
  _globals['_PAYMENTSERVICE']._serialized_start=377
  _globals['_PAYMENTSERVICE']._serialized_end=660
# @@protoc_insertion_point(module_scope)
