# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fraud_detection_pb2 as fraud__detection__pb2


class FraudDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitOrder = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/InitOrder',
                request_serializer=fraud__detection__pb2.InitOrderRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.InitOrderResponse.FromString,
                )
        self.CheckUserDataForFraud = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/CheckUserDataForFraud',
                request_serializer=fraud__detection__pb2.FraudCheckRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.FraudCheckResponse.FromString,
                )
        self.CheckCreditCardForFraud = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/CheckCreditCardForFraud',
                request_serializer=fraud__detection__pb2.FraudCheckRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.FraudCheckResponse.FromString,
                )
        self.ClearOrder = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/ClearOrder',
                request_serializer=fraud__detection__pb2.ClearOrderRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.ClearOrderResponse.FromString,
                )


class FraudDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserDataForFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCreditCardForFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=fraud__detection__pb2.InitOrderRequest.FromString,
                    response_serializer=fraud__detection__pb2.InitOrderResponse.SerializeToString,
            ),
            'CheckUserDataForFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserDataForFraud,
                    request_deserializer=fraud__detection__pb2.FraudCheckRequest.FromString,
                    response_serializer=fraud__detection__pb2.FraudCheckResponse.SerializeToString,
            ),
            'CheckCreditCardForFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCreditCardForFraud,
                    request_deserializer=fraud__detection__pb2.FraudCheckRequest.FromString,
                    response_serializer=fraud__detection__pb2.FraudCheckResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=fraud__detection__pb2.ClearOrderRequest.FromString,
                    response_serializer=fraud__detection__pb2.ClearOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud_detection.FraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FraudDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/InitOrder',
            fraud__detection__pb2.InitOrderRequest.SerializeToString,
            fraud__detection__pb2.InitOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckUserDataForFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/CheckUserDataForFraud',
            fraud__detection__pb2.FraudCheckRequest.SerializeToString,
            fraud__detection__pb2.FraudCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckCreditCardForFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/CheckCreditCardForFraud',
            fraud__detection__pb2.FraudCheckRequest.SerializeToString,
            fraud__detection__pb2.FraudCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/ClearOrder',
            fraud__detection__pb2.ClearOrderRequest.SerializeToString,
            fraud__detection__pb2.ClearOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
