# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import books_database_pb2 as books__database__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in books_database_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BooksDatabaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/books_database.BooksDatabaseService/Read',
                request_serializer=books__database__pb2.ReadRequest.SerializeToString,
                response_deserializer=books__database__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/books_database.BooksDatabaseService/Write',
                request_serializer=books__database__pb2.WriteRequest.SerializeToString,
                response_deserializer=books__database__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.ReadLocal = channel.unary_unary(
                '/books_database.BooksDatabaseService/ReadLocal',
                request_serializer=books__database__pb2.ReadRequest.SerializeToString,
                response_deserializer=books__database__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.ReplicateWrite = channel.unary_unary(
                '/books_database.BooksDatabaseService/ReplicateWrite',
                request_serializer=books__database__pb2.ReplicateWriteRequest.SerializeToString,
                response_deserializer=books__database__pb2.ReplicateWriteResponse.FromString,
                _registered_method=True)
        self.WhoIsPrimary = channel.unary_unary(
                '/books_database.BooksDatabaseService/WhoIsPrimary',
                request_serializer=books__database__pb2.WhoIsPrimaryRequest.SerializeToString,
                response_deserializer=books__database__pb2.WhoIsPrimaryResponse.FromString,
                _registered_method=True)
        self.Election = channel.unary_unary(
                '/books_database.BooksDatabaseService/Election',
                request_serializer=books__database__pb2.ElectionRequest.SerializeToString,
                response_deserializer=books__database__pb2.ElectionResponse.FromString,
                _registered_method=True)
        self.Coordinator = channel.unary_unary(
                '/books_database.BooksDatabaseService/Coordinator',
                request_serializer=books__database__pb2.CoordinatorRequest.SerializeToString,
                response_deserializer=books__database__pb2.Ack.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/books_database.BooksDatabaseService/Heartbeat',
                request_serializer=books__database__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=books__database__pb2.Ack.FromString,
                _registered_method=True)
        self.Prepare = channel.unary_unary(
                '/books_database.BooksDatabaseService/Prepare',
                request_serializer=books__database__pb2.PrepareRequest.SerializeToString,
                response_deserializer=books__database__pb2.PrepareResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/books_database.BooksDatabaseService/Commit',
                request_serializer=books__database__pb2.CommitRequest.SerializeToString,
                response_deserializer=books__database__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/books_database.BooksDatabaseService/Abort',
                request_serializer=books__database__pb2.AbortRequest.SerializeToString,
                response_deserializer=books__database__pb2.AbortResponse.FromString,
                _registered_method=True)


class BooksDatabaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Read(self, request, context):
        """Client-facing RPCs. In Phase 2 clients should send these to the primary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadLocal(self, request, context):
        """Debug/ops RPC that reads the local replica's copy without the
        primary-only check. Used by the convergence check in
        scripts/checkpoint3-checks.ps1 to verify that all three replicas hold
        the same value after a committed write. Never used by the orchestrator
        or the 2PC coordinator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateWrite(self, request, context):
        """Internal: primary -> backup synchronous replication of a committed write.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhoIsPrimary(self, request, context):
        """Primary discovery. Any replica answers; the response points to the
        replica that currently believes itself to be primary (or replies
        leader_id=0 if no primary is known yet).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Election(self, request, context):
        """Bully-style election, mirroring the pattern already used by the
        order_executor control service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Coordinator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prepare(self, request, context):
        """2PC participant-side RPCs. The primary acts as the participant; backups
        pick up committed state via ReplicateWrite inside Commit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksDatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=books__database__pb2.ReadRequest.FromString,
                    response_serializer=books__database__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=books__database__pb2.WriteRequest.FromString,
                    response_serializer=books__database__pb2.WriteResponse.SerializeToString,
            ),
            'ReadLocal': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadLocal,
                    request_deserializer=books__database__pb2.ReadRequest.FromString,
                    response_serializer=books__database__pb2.ReadResponse.SerializeToString,
            ),
            'ReplicateWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateWrite,
                    request_deserializer=books__database__pb2.ReplicateWriteRequest.FromString,
                    response_serializer=books__database__pb2.ReplicateWriteResponse.SerializeToString,
            ),
            'WhoIsPrimary': grpc.unary_unary_rpc_method_handler(
                    servicer.WhoIsPrimary,
                    request_deserializer=books__database__pb2.WhoIsPrimaryRequest.FromString,
                    response_serializer=books__database__pb2.WhoIsPrimaryResponse.SerializeToString,
            ),
            'Election': grpc.unary_unary_rpc_method_handler(
                    servicer.Election,
                    request_deserializer=books__database__pb2.ElectionRequest.FromString,
                    response_serializer=books__database__pb2.ElectionResponse.SerializeToString,
            ),
            'Coordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.Coordinator,
                    request_deserializer=books__database__pb2.CoordinatorRequest.FromString,
                    response_serializer=books__database__pb2.Ack.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=books__database__pb2.HeartbeatRequest.FromString,
                    response_serializer=books__database__pb2.Ack.SerializeToString,
            ),
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=books__database__pb2.PrepareRequest.FromString,
                    response_serializer=books__database__pb2.PrepareResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=books__database__pb2.CommitRequest.FromString,
                    response_serializer=books__database__pb2.CommitResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=books__database__pb2.AbortRequest.FromString,
                    response_serializer=books__database__pb2.AbortResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books_database.BooksDatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('books_database.BooksDatabaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BooksDatabaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books_database.BooksDatabaseService/Read',
            books__database__pb2.ReadRequest.SerializeToString,
            books__database__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books_database.BooksDatabaseService/Write',
            books__database__pb2.WriteRequest.SerializeToString,
            books__database__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadLocal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books_database.BooksDatabaseService/ReadLocal',
            books__database__pb2.ReadRequest.SerializeToString,
            books__database__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books_database.BooksDatabaseService/ReplicateWrite',
            books__database__pb2.ReplicateWriteRequest.SerializeToString,
            books__database__pb2.ReplicateWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WhoIsPrimary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books_database.BooksDatabaseService/WhoIsPrimary',
            books__database__pb2.WhoIsPrimaryRequest.SerializeToString,
            books__database__pb2.WhoIsPrimaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Election(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books_database.BooksDatabaseService/Election',
            books__database__pb2.ElectionRequest.SerializeToString,
            books__database__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Coordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books_database.BooksDatabaseService/Coordinator',
            books__database__pb2.CoordinatorRequest.SerializeToString,
            books__database__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books_database.BooksDatabaseService/Heartbeat',
            books__database__pb2.HeartbeatRequest.SerializeToString,
            books__database__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books_database.BooksDatabaseService/Prepare',
            books__database__pb2.PrepareRequest.SerializeToString,
            books__database__pb2.PrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books_database.BooksDatabaseService/Commit',
            books__database__pb2.CommitRequest.SerializeToString,
            books__database__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books_database.BooksDatabaseService/Abort',
            books__database__pb2.AbortRequest.SerializeToString,
            books__database__pb2.AbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
