# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books_database.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ooks_database.proto\x12\x0e\x62ooks_database\"!\n\x0bReadRequest\x12\x12\n\nbook_title\x18\x01 \x01(\t\"@\n\x0cReadResponse\x12\x12\n\nbook_title\x18\x01 \x01(\t\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\r\n\x05\x66ound\x18\x03 \x01(\x08\"V\n\x0cWriteRequest\x12\x12\n\nbook_title\x18\x01 \x01(\t\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\x12\x0b\n\x03seq\x18\x04 \x01(\x05\"1\n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"`\n\x0ePrepareRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x12\n\nbook_title\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"D\n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tnew_stock\x18\x03 \x01(\x05\"9\n\rCommitRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\"2\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"8\n\x0c\x41\x62ortRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\" \n\rAbortResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xfa\x02\n\x14\x42ooksDatabaseService\x12\x41\n\x04Read\x12\x1b.books_database.ReadRequest\x1a\x1c.books_database.ReadResponse\x12\x44\n\x05Write\x12\x1c.books_database.WriteRequest\x1a\x1d.books_database.WriteResponse\x12J\n\x07Prepare\x12\x1e.books_database.PrepareRequest\x1a\x1f.books_database.PrepareResponse\x12G\n\x06\x43ommit\x12\x1d.books_database.CommitRequest\x1a\x1e.books_database.CommitResponse\x12\x44\n\x05\x41\x62ort\x12\x1c.books_database.AbortRequest\x1a\x1d.books_database.AbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_database_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_READREQUEST']._serialized_start=40
  _globals['_READREQUEST']._serialized_end=73
  _globals['_READRESPONSE']._serialized_start=75
  _globals['_READRESPONSE']._serialized_end=139
  _globals['_WRITEREQUEST']._serialized_start=141
  _globals['_WRITEREQUEST']._serialized_end=227
  _globals['_WRITERESPONSE']._serialized_start=229
  _globals['_WRITERESPONSE']._serialized_end=278
  _globals['_PREPAREREQUEST']._serialized_start=280
  _globals['_PREPAREREQUEST']._serialized_end=376
  _globals['_PREPARERESPONSE']._serialized_start=378
  _globals['_PREPARERESPONSE']._serialized_end=446
  _globals['_COMMITREQUEST']._serialized_start=448
  _globals['_COMMITREQUEST']._serialized_end=505
  _globals['_COMMITRESPONSE']._serialized_start=507
  _globals['_COMMITRESPONSE']._serialized_end=557
  _globals['_ABORTREQUEST']._serialized_start=559
  _globals['_ABORTREQUEST']._serialized_end=615
  _globals['_ABORTRESPONSE']._serialized_start=617
  _globals['_ABORTRESPONSE']._serialized_end=649
  _globals['_BOOKSDATABASESERVICE']._serialized_start=652
  _globals['_BOOKSDATABASESERVICE']._serialized_end=1030
# @@protoc_insertion_point(module_scope)
