# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_queue.proto\x12\x0border_queue\"Q\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x14\n\x0cuser_contact\x18\x03 \x01(\t\x12\r\n\x05items\x18\x04 \x03(\t\"3\n\x0e\x45nqueueRequest\x12!\n\x05order\x18\x01 \x01(\x0b\x32\x12.order_queue.Order\"3\n\x0f\x45nqueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x0e\x44\x65queueRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\"V\n\x0f\x44\x65queueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12!\n\x05order\x18\x02 \x01(\x0b\x32\x12.order_queue.Order\x12\x0f\n\x07message\x18\x03 \x01(\t2\x9f\x01\n\x11OrderQueueService\x12\x44\n\x07\x45nqueue\x12\x1b.order_queue.EnqueueRequest\x1a\x1c.order_queue.EnqueueResponse\x12\x44\n\x07\x44\x65queue\x12\x1b.order_queue.DequeueRequest\x1a\x1c.order_queue.DequeueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDER']._serialized_start=34
  _globals['_ORDER']._serialized_end=115
  _globals['_ENQUEUEREQUEST']._serialized_start=117
  _globals['_ENQUEUEREQUEST']._serialized_end=168
  _globals['_ENQUEUERESPONSE']._serialized_start=170
  _globals['_ENQUEUERESPONSE']._serialized_end=221
  _globals['_DEQUEUEREQUEST']._serialized_start=223
  _globals['_DEQUEUEREQUEST']._serialized_end=260
  _globals['_DEQUEUERESPONSE']._serialized_start=262
  _globals['_DEQUEUERESPONSE']._serialized_end=348
  _globals['_ORDERQUEUESERVICE']._serialized_start=351
  _globals['_ORDERQUEUESERVICE']._serialized_end=510
# @@protoc_insertion_point(module_scope)
