# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transaction_verification_pb2 as transaction__verification__pb2


class TransactionVerificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/InitOrder',
                request_serializer=transaction__verification__pb2.InitOrderRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.InitOrderResponse.FromString,
                )
        self.VerifyItems = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/VerifyItems',
                request_serializer=transaction__verification__pb2.VerifyRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.VerifyResponse.FromString,
                )
        self.VerifyUserData = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/VerifyUserData',
                request_serializer=transaction__verification__pb2.VerifyRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.VerifyResponse.FromString,
                )
        self.VerifyCardFormat = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/VerifyCardFormat',
                request_serializer=transaction__verification__pb2.VerifyRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.VerifyResponse.FromString,
                )
        self.ClearOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/ClearOrder',
                request_serializer=transaction__verification__pb2.ClearOrderRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.ClearOrderResponse.FromString,
                )


class TransactionVerificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCardFormat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionVerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=transaction__verification__pb2.InitOrderRequest.FromString,
                    response_serializer=transaction__verification__pb2.InitOrderResponse.SerializeToString,
            ),
            'VerifyItems': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyItems,
                    request_deserializer=transaction__verification__pb2.VerifyRequest.FromString,
                    response_serializer=transaction__verification__pb2.VerifyResponse.SerializeToString,
            ),
            'VerifyUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyUserData,
                    request_deserializer=transaction__verification__pb2.VerifyRequest.FromString,
                    response_serializer=transaction__verification__pb2.VerifyResponse.SerializeToString,
            ),
            'VerifyCardFormat': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCardFormat,
                    request_deserializer=transaction__verification__pb2.VerifyRequest.FromString,
                    response_serializer=transaction__verification__pb2.VerifyResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=transaction__verification__pb2.ClearOrderRequest.FromString,
                    response_serializer=transaction__verification__pb2.ClearOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction_verification.TransactionVerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionVerificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/InitOrder',
            transaction__verification__pb2.InitOrderRequest.SerializeToString,
            transaction__verification__pb2.InitOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/VerifyItems',
            transaction__verification__pb2.VerifyRequest.SerializeToString,
            transaction__verification__pb2.VerifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/VerifyUserData',
            transaction__verification__pb2.VerifyRequest.SerializeToString,
            transaction__verification__pb2.VerifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyCardFormat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/VerifyCardFormat',
            transaction__verification__pb2.VerifyRequest.SerializeToString,
            transaction__verification__pb2.VerifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/ClearOrder',
            transaction__verification__pb2.ClearOrderRequest.SerializeToString,
            transaction__verification__pb2.ClearOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
