# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x18transaction_verification\"\x1d\n\x0bVectorClock\x12\x0e\n\x06values\x18\x01 \x03(\x05\",\n\tOrderItem\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\xe1\x01\n\tOrderData\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x14\n\x0cuser_contact\x18\x03 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x04 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x05 \x01(\t\x12\x0b\n\x03\x63vv\x18\x06 \x01(\t\x12\x12\n\nitem_count\x18\x07 \x01(\x05\x12\x16\n\x0eterms_accepted\x18\x08 \x01(\x08\x12\x32\n\x05items\x18\t \x03(\x0b\x32#.transaction_verification.OrderItem\"F\n\x10InitOrderRequest\x12\x32\n\x05order\x18\x01 \x01(\x0b\x32#.transaction_verification.OrderData\"S\n\x0c\x45ventRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x31\n\x02vc\x18\x02 \x01(\x0b\x32%.transaction_verification.VectorClock\"d\n\rEventResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x31\n\x02vc\x18\x03 \x01(\x0b\x32%.transaction_verification.VectorClock\"^\n\x11\x43learOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x37\n\x08\x66inal_vc\x18\x02 \x01(\x0b\x32%.transaction_verification.VectorClock2\x94\x04\n\x1eTransactionVerificationService\x12`\n\tInitOrder\x12*.transaction_verification.InitOrderRequest\x1a\'.transaction_verification.EventResponse\x12`\n\rValidateItems\x12&.transaction_verification.EventRequest\x1a\'.transaction_verification.EventResponse\x12\x63\n\x10ValidateUserData\x12&.transaction_verification.EventRequest\x1a\'.transaction_verification.EventResponse\x12\x65\n\x12ValidateCardFormat\x12&.transaction_verification.EventRequest\x1a\'.transaction_verification.EventResponse\x12\x62\n\nClearOrder\x12+.transaction_verification.ClearOrderRequest\x1a\'.transaction_verification.EventResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORCLOCK']._serialized_start=60
  _globals['_VECTORCLOCK']._serialized_end=89
  _globals['_ORDERITEM']._serialized_start=91
  _globals['_ORDERITEM']._serialized_end=135
  _globals['_ORDERDATA']._serialized_start=138
  _globals['_ORDERDATA']._serialized_end=363
  _globals['_INITORDERREQUEST']._serialized_start=365
  _globals['_INITORDERREQUEST']._serialized_end=435
  _globals['_EVENTREQUEST']._serialized_start=437
  _globals['_EVENTREQUEST']._serialized_end=520
  _globals['_EVENTRESPONSE']._serialized_start=522
  _globals['_EVENTRESPONSE']._serialized_end=622
  _globals['_CLEARORDERREQUEST']._serialized_start=624
  _globals['_CLEARORDERREQUEST']._serialized_end=718
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=721
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=1253
# @@protoc_insertion_point(module_scope)
