# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x0eorder_executor\"\'\n\x0f\x45lectionRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\t\"(\n\x10\x45lectionResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"\"\n\rLeaderRequest\x12\x11\n\tleader_id\x18\x01 \x01(\t\"&\n\x0eLeaderResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"\x12\n\x10GetLeaderRequest\"&\n\x11GetLeaderResponse\x12\x11\n\tleader_id\x18\x01 \x01(\t2\x8d\x02\n\x14OrderExecutorService\x12R\n\rStartElection\x12\x1f.order_executor.ElectionRequest\x1a .order_executor.ElectionResponse\x12O\n\x0e\x41nnounceLeader\x12\x1d.order_executor.LeaderRequest\x1a\x1e.order_executor.LeaderResponse\x12P\n\tGetLeader\x12 .order_executor.GetLeaderRequest\x1a!.order_executor.GetLeaderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ELECTIONREQUEST']._serialized_start=40
  _globals['_ELECTIONREQUEST']._serialized_end=79
  _globals['_ELECTIONRESPONSE']._serialized_start=81
  _globals['_ELECTIONRESPONSE']._serialized_end=121
  _globals['_LEADERREQUEST']._serialized_start=123
  _globals['_LEADERREQUEST']._serialized_end=157
  _globals['_LEADERRESPONSE']._serialized_start=159
  _globals['_LEADERRESPONSE']._serialized_end=197
  _globals['_GETLEADERREQUEST']._serialized_start=199
  _globals['_GETLEADERREQUEST']._serialized_end=217
  _globals['_GETLEADERRESPONSE']._serialized_start=219
  _globals['_GETLEADERRESPONSE']._serialized_end=257
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=260
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=529
# @@protoc_insertion_point(module_scope)
